LINKEDIN_URL = 'https://www.linkedin.com/login'
NAUKRI_URL = "https://www.naukri.com/"

USERNAME = "harshal.shinde1075@gmail.com"
PASSWORD = "Harsh@555"

JOB_SEARCH_TITLES = 'SDET, python test automation, Software testing, Automation testing, software developer engineer in test, python automation test engineer, '
JOB_SEARCH_LOCATIONS = 'Pune, Bengaluru, Indore, India, Hyderabad, '

LINKEDIN_JOB_SEARCH_TITLES = 'SDET' #'python test automation'
LINKEDIN_JOB_SEARCH_LOCATIONS = 'India'

USER_FULL_NAME = "Harshal Suryakant Shinde"

YEARS_OF_EXPERIENCE_IN_CORE = '5'
YEARS_OF_EXPERIENCE_IN_NON_CORE = '3'

EXPECTED_CTC_FULL_NUMERIC = '1500000'
CURRENT_CTC_FULL_NUMERIC = '700000'

EXPECTED_CTC_NUMERIC = '15'
CURRENT_CTC_NUMERIC = '7'

ANSWER_YES = 'YES'
ANSWER_NO = 'NO'
ANSWER_NOT_APPLICABLE = 'NA'
ANSWER_ALL = 'ALL'

PROGRAMMING_LANGUAGE = 'Python'
CURRENT_ORGANIZATION = 'SASKEN Technology (ABB INDIA)'

FIRST_NAME = 'Harshal'
LAST_NAME = 'Shinde'
DATE_OF_BIRTH = '29/12/1998'
GENDER = 'Male'
COUNTRY_CODE = '+91'
MOBILE_NUMBER = '9168921075'

CURRENT_LOCATION = 'Bengaluru, Karnataka, India'
PREFERRED_LOCATION = 'Pune, Bengaluru, Remote, Any city in india'
CURRENT_LOCATION_IS_BANGALORE = 'Currently staying in bengaluru'
NOTICE_PERIOD_IN_DAYS = '15'
OFFICIAL_NOTICE_PERIOD_IN_DAYS = '60'
SKILLS = "Manual Testing, Automated Testing, API, Playwright, PyTest, Postman, Selenium, Accessibility Testing, CI/CD Pipeline Configuration, Cross-Browser Testing & Responsive Testing"
ROLE_CATEGORY_SECTION = 'Quality Assurance and Testing'  ## Dev 'Software Development'

question_answer_map = {
    "What is your Notice Period?":NOTICE_PERIOD_IN_DAYS,
    "What is your expected CTC in LPA?":EXPECTED_CTC_NUMERIC,
    "How many years of work experience do you have with Git?":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Coding Practices?":YEARS_OF_EXPERIENCE_IN_CORE,
    "What is your relevant experience?":YEARS_OF_EXPERIENCE_IN_CORE,
    "Full Name":USER_FULL_NAME,
    "How many years of experience do you have in Ios Testing?":YEARS_OF_EXPERIENCE_IN_CORE,
    "Are you comfortable working in Bangalore in Hybrid mode?":ANSWER_YES,
    "Are you currently residing in Kochi, Kerala or willing to relocate to Kochi, Kerala?":YEARS_OF_EXPERIENCE_IN_CORE,
    "Total Expereince":YEARS_OF_EXPERIENCE_IN_CORE,
    "Do you have hands-on experience in Python?":YEARS_OF_EXPERIENCE_IN_CORE,
    "What is your current CTC (in LPA)?":CURRENT_CTC_NUMERIC,
    "How many years of hands-on DevOps experience do you have in production environments?":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Application Programming Interfaces (API)?":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in UI Automation?":YEARS_OF_EXPERIENCE_IN_CORE,
    "How soon will you be able to start? (in days)":NOTICE_PERIOD_IN_DAYS,
    "What is your current notice period?":NOTICE_PERIOD_IN_DAYS,
    "Current CTC:":CURRENT_CTC_NUMERIC,
    "How many years of work experience do you have with Laboratory Information Management System (LIMS)?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How Many Years of experience do you have in Selenium?":YEARS_OF_EXPERIENCE_IN_CORE,
    "Desired Salary (Numeric Input Only)":CURRENT_CTC_NUMERIC,
    "What is your total experience":YEARS_OF_EXPERIENCE_IN_CORE,
    "Do you have PF A/C in current & Pervious organization?":ANSWER_YES,
    "How many years of experience do you have in Appium?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "Do you have 2-5 Years of Experience?":ANSWER_YES,
    "Are you available for F2F on 14th June from Bangalore?":ANSWER_YES,
    "How many Years of experiance do you have in Playwrite?":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Selenium with Java?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "What is your total exp?":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of working Playwright experience?":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many Years of experiance do you have in Appium ?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in Typescript?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in API?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have Database Tech Lead?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with AWS / Azure":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with VBA Excel?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "what is your experience with Unix or Linux environment":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Automation Architecture ?":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with ISO8583?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Quality Assurance Audits?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Configure Price Quote (CPQ) Software?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "Years many years of Experience you have in Python":YEARS_OF_EXPERIENCE_IN_CORE,
    "What is your Expected CTC/Salary?":EXPECTED_CTC_NUMERIC,
    "How many years of work experience do you have with Joint Test Action Group (JTAG)?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Snowflake?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with SSIS":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with System on a Chip (SoC)?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "Databricks, Pyspark and Data Factory Experience Minimum 6 Yrs ?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with SAP Sales & Distribution?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with NICE Call Recording?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Motion Control?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with JMeter?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have in Automation testing?":YEARS_OF_EXPERIENCE_IN_CORE,
    "What’s your current salary? (in lakhs per annum)":CURRENT_CTC_NUMERIC,
    "How many years of experience do you have in Quality Assurance (manual) for web-based or cloud-delivered products? (Should reflect in resume)":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience you have in API testing suits":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of professional experience do you have in the field of Quality Assurance?":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of Consulting experience do you currently have?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Azure-CI/CD Pipeline?":YEARS_OF_EXPERIENCE_IN_CORE,
    "What's your current CTC?":CURRENT_CTC_NUMERIC,
    "How many years of experience do you have in Automation testing?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in C#?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in Layer 2?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have in product manual functional testing and quality assurance?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience in Automation testing ?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Performance Testing?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "Do you have any experience in AnyLogic or FlexSim Tool ?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in Webdriver?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Programming language(and in which on -Java or Python or C)?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Selenium Testing?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Are you ready for 5 Days WFO at Client location(Pune)?":ANSWER_YES ,
    "How many years of experience do you have in L3?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Are you an Immediate Joiner?": ANSWER_YES,
    "Do you have 4+ Years of automation? Please specify your responsibility as automation engineer?": "Framework Development, UI Automation, API Automation",
    "How many years of experience in CI/CD pipeline?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Expense Allocation?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of Semiconductor Manufacturing experience do you currently have?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Aircraft Maintenance?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "Current CTC?": CURRENT_CTC_NUMERIC,
    "How many years of work experience do you have with Java/C# ?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in deploying AI projects for real world problems?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Delphi?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Azure Functions?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "What is your current location?": CURRENT_LOCATION,
    "Currently located in Hyderabad":ANSWER_NO,
    "Relevant Experience with Advanced SQL?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "Doyou have experience in Python or C#?":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years experience do you have in AWS Glue? *":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in Cucumber?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "Strong scripting knowledge in Beanshell/ Java/Python programming??":YEARS_OF_EXPERIENCE_IN_CORE,
    "If hired, how soon can you start?":NOTICE_PERIOD_IN_DAYS,
    "How many years of experience do you have in X-Ray?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with NeoLoad?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many Years of experience implementing or using data validation and quality assurance frameworks": YEARS_OF_EXPERIENCE_IN_CORE,
    "Total Exp": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with TypeScript?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "Are you ready for an F2F interview on 11th June (Wednesday) in Noida?":ANSWER_YES,
    "How Many years of Experience you have in Automation testing?":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years experience do you have in Automation Testing?":YEARS_OF_EXPERIENCE_IN_CORE,
    "How much Relevant experience in Automation ?":YEARS_OF_EXPERIENCE_IN_CORE,
    "how many years into J meter ??":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have as an Automation Quality Test Engineer?":YEARS_OF_EXPERIENCE_IN_CORE,
    "How much experience you have BGP & OSPF Networking protocols?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "Are you available for Face-to-Face Interview at 22nd February 2025 (Saturday)..?":ANSWER_YES,
    "How many years of experience you have in Java, Selenium?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in BDD?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "PAN Number (Mandatory for uploading your profile)":'HOQPS3028F',
    "Are you an immediate joiner? Can you join us within 7 days?":ANSWER_YES,
    "How many years of experience in python with selenium":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Automation Testing ?":YEARS_OF_EXPERIENCE_IN_CORE,
    "SALUTATION":'Mr.',
    "Are you currently residing in Ahmedabad or willing to relocate to Ahmedabad or Abu Dhabi?":ANSWER_YES,
    "How much experience you have in Python Automation Testing?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in API testing?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Full Name as per Aadhar? and Current Payroll Company Name?": f'{USER_FULL_NAME} & {CURRENT_ORGANIZATION}',
    "How many years of experience do you have in Playwright Automation?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Relevant Experience as QA - Quality Assurance Engineer?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Salutation": 'Mr.',
    "How many years of work experience do you have with Global Distribution Systems (GDS)?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "Current company": CURRENT_ORGANIZATION,
    "How many years of work experience do you have with Embedded testing": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with DWH?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "Start Date": NOTICE_PERIOD_IN_DAYS,
    "How many years of work experience do you have with Java Database Connectivity (JDBC)?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with SAP Cloud Platform?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Cash Management?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Total Experience": YEARS_OF_EXPERIENCE_IN_CORE,
    "City": CURRENT_LOCATION,
    "Total Year experience": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you hold with penetration testing tools and methodologies – PTES, NIST 800-115, OWASP": ANSWER_YES,
    "how much is your expected CTC": CURRENT_CTC_NUMERIC,
    "How many years of work experience do you have with Oracle Applications?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Cypress is mandatory .How many years of experience do you have in Cypress?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Your Last working date?If serving notice period?": NOTICE_PERIOD_IN_DAYS,
    "How much can you rate on your communication skills out of 5?": '5',
    "What is your notice period?(Days or LWD:DD/MM/YYYY)": NOTICE_PERIOD_IN_DAYS,
    "What's your current salary?": CURRENT_CTC_NUMERIC,
    "How many years of experience do you have in Selenium With Java?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Are you can immediate joiner? Whats your notice period?": NOTICE_PERIOD_IN_DAYS,
    "How many years of experience do you have with maintaining test automation frameworks using Playwright with Python/Java Script?":YEARS_OF_EXPERIENCE_IN_CORE,
    "What is your total years of experience?":YEARS_OF_EXPERIENCE_IN_CORE,
    "What are your annual salary expectations? (Enter base salary amount in rupees like if salary expectations are 12 lakhs then enter 1200000)":EXPECTED_CTC_FULL_NUMERIC,
    "How many years of work experience do you have as a Test Analyst or Engineer?":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with testing scripts using Platform?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with scripting language (Java, Groovy, Beamshell)?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Cisco Systems Products?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "What is your Exit Date updated in the System as we are looking only people who are immediate joiner ?":ANSWER_YES,
    "Relevant Experience with Java/Python (Coding)?":YEARS_OF_EXPERIENCE_IN_CORE,
    "Do you have hands on experience with Accessibility Testing? Mention the no.of years below":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in SDET?":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Atm Testing?":YEARS_OF_EXPERIENCE_IN_CORE,
    "Are you currently residing in Salem, Tamil Nadu or willing to relocate to Salem, Tamil Nadu?":ANSWER_YES,
    "Phone": MOBILE_NUMBER,
    "How many years of work experience do you have as a Quality Assurance Engineer?":YEARS_OF_EXPERIENCE_IN_CORE,
    "Relevant Experience with ETL Testing?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "Total IT Exp.?":YEARS_OF_EXPERIENCE_IN_CORE,
    "Which Location would you Prefer -": PREFERRED_LOCATION,
    "Do you have a minimum of 70% marks in all your academic qualifications (schooling and higher education)?":ANSWER_YES,
    "How many years of experience do you have in Manual And Automation Testing?":YEARS_OF_EXPERIENCE_IN_CORE,
    "Are you currently residing in Chennai, Tamil Nadu or willing to relocate to Chennai, Tamil Nadu?":ANSWER_YES,
    "How many years of experience do you have in Mobile Testing?":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience in API Testing?":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Cloud?":YEARS_OF_EXPERIENCE_IN_CORE,
    "Current CTC? And Expected CTC?":f'{CURRENT_CTC_NUMERIC} & {EXPECTED_CTC_NUMERIC}',
    "How many years of experience do you have in API Testing ?":YEARS_OF_EXPERIENCE_IN_CORE,
    "Are you available for F2F interview on June 14th ??":ANSWER_YES,
    "Skill Category": "Python, Playwright, pytest, UI Automation, UI Automation, Postman, Azure DevOps",
    "How many years of experience do you have in JIRA?":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Operating System Administration?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in Golang?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in Manual Testing ?":	YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Data Warehousing?":	YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in Data Warehouse Testing?":YEARS_OF_EXPERIENCE_IN_NON_CORE	,
    "How many years of experience do you have in ETL testing?":	YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "Aadhaar Number":'281263544960',
    "How many years of work experience do you have with JavaScript?":YEARS_OF_EXPERIENCE_IN_CORE,
    "Please provide your Pan Card number?":'HOQPS3028F',
    "How many years of experience do you have in API Testing?":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Functional Testing?":YEARS_OF_EXPERIENCE_IN_CORE,
    "Have you previously worked at Skillsoft as an employee, intern, or contractor?":ANSWER_NO,
    "How many years of work experience do you have with C (Programming Language)?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with sitecore ?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Mainframe Developing ?": YEARS_OF_EXPERIENCE_IN_CORE,
    "What is your desired CTC?": EXPECTED_CTC_NUMERIC,
    "Current Location (City)": CURRENT_LOCATION,
    "Are your available for in-person interview on Tuesday-3-June-2025": ANSWER_YES,
    "Are you comfortable working at Client's office in Chennai?": ANSWER_YES,
    "Are you ready to relocate to Bangalore?": ANSWER_YES,
    "Total Experience(In years)": YEARS_OF_EXPERIENCE_IN_CORE,
    "Current Company Name:": CURRENT_ORGANIZATION,
    "Preferred Name": USER_FULL_NAME,
    "This is fulltime employment V3 Staffing and Deputed in Client Place - Are you interested??":ANSWER_YES,
    "How many years of work experience do you have with Amazon Web Services (AWS)?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have as a ETL Testing ?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Architects?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with API Testing?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Years of experience as a Software Engineer, or Software Development Engineer in Test?": YEARS_OF_EXPERIENCE_IN_CORE,
    "What is Expected CTC/Salary per annum?": EXPECTED_CTC_NUMERIC,
    "Whats your CTC?": CURRENT_CTC_NUMERIC,
    "How many years of work experience do you have with Java/J2EE?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "Are you proficient in at least two of the following programming languages: JavaScript, Python, Go, Java, TypeScript, or C++?": ANSWER_YES,
    "How many years of work experience do you have with Medical Device Quality Assurance?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with IRIS?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience with Cargo Platform implementing forwarding and transportation management functions. ?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "What is your total work experience ?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Playwriting?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of professional experience do you have in software testing and quality assurance": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of total experience do you have?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Python Testing?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Automation test?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Nationality": "Indian",
    "Middle Name": "Suryakant",
    "How much experience do you have?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Are you willing to come down to the Office for a Walkin (Bangalore)": ANSWER_YES,
    "What is your current location and preferred location ?": CURRENT_LOCATION,
    "How many years of experience do you have in automation testing?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Python Automation?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many Years of Automation Testing Experience do you have": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Automation Testing?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with QA Manual?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Previously Employed by Cognizant": ANSWER_NO,
    "Can you join within 30 Days?": ANSWER_YES,
    "How many years of experience do you have in UNIX?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in Data Bricks?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in Web Application Testing?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have in Performance Testing using Jmeter?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "ECTC": EXPECTED_CTC_NUMERIC,
    "Current CTC ?": EXPECTED_CTC_NUMERIC,
    "How many years of work experience do you have with Application Development?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "Expected CTC (in LPA)": EXPECTED_CTC_NUMERIC,
    "are you currently serving your notice ? if so how many days you have left ?": NOTICE_PERIOD_IN_DAYS,
    "What is your monthly salary expectation? In Indian Rupee.": EXPECTED_CTC_NUMERIC,
    "How many years of work experience do you have with Azure Kubernetes Service (AKS)?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Alfresco Software?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "What is your current notice period ?": NOTICE_PERIOD_IN_DAYS,
    "How many years of work experience do you have with CPI?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with DevOps?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have as a AI/ML Engineer?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many days of notice period do you have?": NOTICE_PERIOD_IN_DAYS,
    "How many years of work experience do you have with File Systems?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Playwright": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience you have with Automation testing ?": YEARS_OF_EXPERIENCE_IN_CORE,
    "what is your current CTC? (In LPA)": CURRENT_CTC_NUMERIC,
    "Notice period ? (In days)": NOTICE_PERIOD_IN_DAYS,
    "How many years into Rest Assured?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "What is your total work experience?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How soon can you join?": NOTICE_PERIOD_IN_DAYS,
    "How many years of experience do you have in total?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Performance Testing?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Worksoft Certify?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience with Ansible?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "What is your current CTC in LPA": CURRENT_CTC_NUMERIC,
    "How many years of exp in Software development (Java or Golang)?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Backend development?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Azure / GCP (Cloud Deployment)?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience in ML Ops?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Large Language Model Operations (LLMOps)?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Next.js?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of Quality Assurance experience do you currently have?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Appium": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Rest API ?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Django?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Appian?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "Deep expertise in multiple languages, with significant experience in.NET (C#),React (JavaScript/TypeScript) Scala and Python": ANSWER_YES,
    "How many years of work experience do you have with Generative AI?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in Generative AI Engineer?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in Machine Learning?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Flutter?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with AWS ?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have as a Andriod Developer ?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in IT ?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Mean Stack?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "Relevant years of experience into gen ai ?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with SD-WAN?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Embedded JavaScript (EJS)?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Mobile Application Development?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have in Automation Anywhere?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How Many years of hands-on experience in front-end technologies (ReactJS, Angular, jQuery, Smart Components).": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of AI/ML experience do you have?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How much is your current CTC? Mention the figure in lacs.": EXPECTED_CTC_NUMERIC,
    "What is your notice period in number of days?": NOTICE_PERIOD_IN_DAYS,
    "What is your official Notice Period?": OFFICIAL_NOTICE_PERIOD_IN_DAYS,
    "What is your current CTC salary in Lakh Per Annum?": CURRENT_CTC_NUMERIC,
    "What is your Current CTC (Fixed)?": CURRENT_CTC_NUMERIC,
    "What was your CGPA in B.Tech./ BCA/ B.Sc./ MCA/ Bachelors degree?": '8.21',
    "How many years of work experience do you have with Python?": YEARS_OF_EXPERIENCE_IN_CORE,
    "What is your total year of experience ?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Representational State Transfer (REST)?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have in Rest API development using JavaScript, Node.js, Java/J2EE, Ruby?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Desired Salary / Expectativa Salarial": EXPECTED_CTC_NUMERIC,
    "Exp in Rest Assured/Robot Framework/Ready API": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of Hibernate experience do you currently have?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many total years of work experience do you have ?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in API automation Testing?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "Your Name": USER_FULL_NAME,
    "Years of experience in automation testing using Python:": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have as a QA Automation Engineer?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have in IT field?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Choose 1/2/3. I studied my 12th in 1) CBSE 2) State Board 3) Other Board": "2",
    "CTC": CURRENT_CTC_NUMERIC,
    "How many years of work experience do you have with IBM Db2?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have as an QA SDET Automation Engineer?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with HTML/CSS Validation?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Middleware?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "Notice period": NOTICE_PERIOD_IN_DAYS,
    "How many years of work experience do you have with Automation Anywhere?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "Are you willing to travel to Perungudi, Chennai?": ANSWER_YES,
    "How many years of work experience do you have with Microservices?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience with Data Conversion Testing | Ab Initio?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "What is your Notice Period": NOTICE_PERIOD_IN_DAYS,
    "How many years of work experience do you have in Automation Testing?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Experience with Debugging skills": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in mobile testing using Appium?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of automation testing experience do you have ?": YEARS_OF_EXPERIENCE_IN_CORE,
    "What are your annual salary expectations?": EXPECTED_CTC_NUMERIC,
    "How many years of experience do you have in Pytest?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience in Automation": YEARS_OF_EXPERIENCE_IN_CORE,
    "Are you currently residing in Noida, Uttar Pradesh or willing to relocate to Noida, Uttar Pradesh?": ANSWER_YES,
    "How many years of experience do you have in SQL?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Embedded Devices?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Linux?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How soon are you available to join (in days)?": NOTICE_PERIOD_IN_DAYS,
    "How many days are left for your notice period?": NOTICE_PERIOD_IN_DAYS,
    "What is your Current CTC?": CURRENT_CTC_NUMERIC,
    "How soon you can join us?": NOTICE_PERIOD_IN_DAYS,
    "What are your salary expectations? (INR)": EXPECTED_CTC_NUMERIC,
    "How many years of work experience do you currently have?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of Proven experience in Software Engineer/ Node.js?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Quality Reporting?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Google Ads?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Salesforce Lightning?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "What is your current CTC per annaum ?": CURRENT_CTC_NUMERIC,
    "How many years of work experience do you have with Machine Tools?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "What is the relevant experience in Manual Testing": YEARS_OF_EXPERIENCE_IN_CORE,
    "Total experience": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Murex?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Spring Framework?": YEARS_OF_EXPERIENCE_IN_CORE,
    "What is your notice period ( in days)?": NOTICE_PERIOD_IN_DAYS,
    "How many years of overall experience do you currently have?": YEARS_OF_EXPERIENCE_IN_CORE,
    "What is your Expected Salary per annum?": EXPECTED_CTC_NUMERIC,
    "Total IT Experience": YEARS_OF_EXPERIENCE_IN_CORE,
    "What is your Notice period in Days?": NOTICE_PERIOD_IN_DAYS,
    "How many years of work experience do you have with Mainframe?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "What did you do during your last professionnal experience?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with LabVIEW?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of hands-on experience you have in Manual testing?": YEARS_OF_EXPERIENCE_IN_CORE,
    "If offered the role, within how many days will you be able to join?": NOTICE_PERIOD_IN_DAYS,
    "How many years of work experience do you have with Azure Data Factory?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "Expected CTC": EXPECTED_CTC_NUMERIC,
    "What is your relevant experince as a Python Developer?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with MATLAB?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Marketing Qualified Lead (MQL)?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in software implementation?": YEARS_OF_EXPERIENCE_IN_CORE,
    "What about this role makes it a good fit for you?": SKILLS,
    "What is your Notice period?": NOTICE_PERIOD_IN_DAYS,
    "How many years of work experience do you have with Hibernate?": YEARS_OF_EXPERIENCE_IN_CORE,
    "What is your current fixed CTC?": CURRENT_CTC_NUMERIC,
    "How many years of work experience do you have with Python backend Development?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Please mention your Current CTC (LPA)": CURRENT_CTC_NUMERIC,
    "What is your expected CTC?": EXPECTED_CTC_NUMERIC,
    "What's your current ctc?":CURRENT_CTC_NUMERIC,
    "How many years of experience do you have in Python and Pytest?":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Computer Architecture?":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Java or Python Programming / Scripting?":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with BDD Frameworks":YEARS_OF_EXPERIENCE_IN_CORE,
    "What is your total experience?":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of Administrative experience do you currently have?":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years experience in Cypress Automation ?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "What is your current CTC":CURRENT_CTC_NUMERIC,
    "How many years of work experience do you have with Data Build Tool (DBT) pipelines, DBT test suites?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "What is your expected salary?":EXPECTED_CTC_NUMERIC,
    "How many years of Software Testing experience do you currently have?":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with IRD?":EXPECTED_CTC_NUMERIC,
    "What is your notice period (in days)?":NOTICE_PERIOD_IN_DAYS,
    "Please Tell us your Current CTC":CURRENT_CTC_NUMERIC,
    "Notice Period?":NOTICE_PERIOD_IN_DAYS,
    "How many years of work experience do you have with Mobile Applications?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years do you have into robotics?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in ETL Testing?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Verilog?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "What is your Expected Annual Salary ?":EXPECTED_CTC_NUMERIC,
    "Yera sof experience QA automation (APIs, UI):":YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Data Cleaning?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Angular?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with FastAPI?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in Manual testing?":YEARS_OF_EXPERIENCE_IN_CORE,
    "Worked for Infosys earlier": ANSWER_NO,
    "How many years of experience do you have in QA Testing?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Composites?": YEARS_OF_EXPERIENCE_IN_CORE,
    "What is your Current Annual Salary?": CURRENT_CTC_NUMERIC,
    "How many years of work experience with Oracle automation | R2R or P2P?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many Years of experience do you have with QA Automation Testing?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have writing automated UI tests using tool MABL ?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience you have in Automation Testing?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with GitHub?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Pyth (Programming Language)?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with AI Software Development?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience with cloud platforms in AWS/Azure?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Rest Assured?": YEARS_OF_EXPERIENCE_IN_CORE,
    "What is your CTC expectation?": EXPECTED_CTC_NUMERIC,
    "How many years of work experience do you have with Android Testing?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have in QA automation?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Java testing tools?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Linux?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Core Java?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in testing Native iOS Applications?": YEARS_OF_EXPERIENCE_IN_CORE,
    "This is a hybrid position that requires you to be in office a minimum 2 days per week. Can you meet this requirement?": ANSWER_YES,
    "Please select the city you are currently residing or willing to relocate to": CURRENT_LOCATION,
    "How many years of experience do you have in Automation Testng?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Do you have experience AI/ML Frameworks like PyTorch or TensorFlow?": ANSWER_YES,
    "How many years of work experience do you have with Pharmaceuticals?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Total yrs of exp": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Manual Testing?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Salesforce Automation?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with International Sales?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with ETL Testing?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Do you have experience working with SAN Functionalaities ?": ANSWER_YES,
    "How many years of work experience do you have with pytest?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in QA Engineer?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in JMeter?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Are you comfortable commuting to this job's location?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Mobile Application Testing?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Programming Languages?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in test engineering?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with VectorCAST?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Karate?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Jira?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "What is your current annual compensation?": CURRENT_CTC_NUMERIC,
    "How many years of work experience do you have with Java 8+?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "Your ECTC ?": EXPECTED_CTC_NUMERIC,
    "What is your expected CTC from Airtel?": EXPECTED_CTC_NUMERIC,
    "Have you received any mail for Recruit.AI@ltts.com ?": ANSWER_NO,
    "Hi Harshal, companies value diversity and want to build inclusive teams. Share your career status to proceed with this job application. Are you on a career break?": ANSWER_NO,
    "How many years of experience do you have in Storage?":YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "We are committed to Thriving Together! Are you able to work in the office at least twice a week?": ANSWER_YES,
    "How many years of work experience do you have with Automation Testing?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Please share your Annual Expected Compensation in INR": EXPECTED_CTC_FULL_NUMERIC,
    "What is your Expected CTC?": EXPECTED_CTC_FULL_NUMERIC,
    "How many years of work experience do you have with REST / SOAP services, KAFKA / MQ event-based applications": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with JUnit?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with data validation and analysis?": YEARS_OF_EXPERIENCE_IN_CORE,
    "What is your Notice Period ?": NOTICE_PERIOD_IN_DAYS,
    "What is your notice period in days?": NOTICE_PERIOD_IN_DAYS,
    "How many years of experience do you have with Selenium with Java?": YEARS_OF_EXPERIENCE_IN_CORE,
    "What is your total years of experience": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Rest Assured Framework?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Playwright?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Years of experience in software testing?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Do you have hands-on experience with Robot Framework?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "ow many years of experience do you have in Robot?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "Have you ever worked on CI/CD pipelines?": ANSWER_YES,
    "What types of testing have you performed (e.g., functional, regression, smoke)?": ANSWER_ALL,
    "Have you ever used Git or any version control systems?": ANSWER_YES,
    "Are you comfortable writing test cases from scratch?": ANSWER_YES,
    "Do you have experience with API testing?": ANSWER_YES,
    "Have you used any cloud-based testing tools or platforms?": ANSWER_YES,
    "Are you familiar with any test management tools like JIRA, TestRail, or Zephyr?": ANSWER_YES,
    "Can you write scripts in any programming language? If so, which ones?": PROGRAMMING_LANGUAGE,
    "Have you worked in an Agile environment?": ANSWER_YES,
    "Do you have experience in mobile testing (Android/iOS)?": ANSWER_YES,
    "Are you familiar with any performance testing tools?": ANSWER_YES,
    "Have you ever contributed to framework development or enhancement?": ANSWER_YES,
    "How many years of work experience in Appium testing": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How much experience do you have with automation frameworks?": YEARS_OF_EXPERIENCE_IN_CORE,
    "What is your current CTC?": CURRENT_CTC_NUMERIC,
    "What is your current CTC? (Fixed + Variable)": CURRENT_CTC_NUMERIC,
    "What is your overall years of experience?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Functional Testing?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of Investment Banking experience do you currently have?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "What is your Experience in C#": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many Years of Experience you have with Cypress E2E?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "What is your exp in automation testing ?": YEARS_OF_EXPERIENCE_IN_CORE,
    "What is your notice period ?": NOTICE_PERIOD_IN_DAYS,
    "How many days notice period you have ?": NOTICE_PERIOD_IN_DAYS,
    "How many years of experience do you have in software testing?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have with SQL?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with QA Engineering?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Selenium and Selenium WebDriver": YEARS_OF_EXPERIENCE_IN_CORE,
    "What is your Total year of Experience": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in QA?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in QA Automation?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Appium?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "What are your years of experience?": YEARS_OF_EXPERIENCE_IN_CORE,
    "What is your official notice period ?": NOTICE_PERIOD_IN_DAYS,
    "Location (city)": CURRENT_LOCATION,
    "How many years of experience do you have as an Python Automation Engineer?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of work experience do you have with Cypress/javascript/playwright? MUST REFLECT IN RESUME.": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with VBScript?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of Information Technology and Services experience do you currently have?": YEARS_OF_EXPERIENCE_IN_CORE,
    "What is your current annual salary in INR?": CURRENT_CTC_FULL_NUMERIC,
    "How many years of work experience do you have with AWS Lambda?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "What is your expected CTC salary in Lakh Per Annum (that will have PF and TDS deductions)?": EXPECTED_CTC_NUMERIC,
    "How many years of work experience do you have with Embedded Systems?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in Robot Framework?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in GitLab?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in AWS?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of work experience do you have with Python (Programming Language)?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Android Testing?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in Mainframe Testing?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in Java?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in python automation?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Total Experience?": YEARS_OF_EXPERIENCE_IN_CORE,
    "What is your Total years of experience?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience you have in quality engineering": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you with Quality Assurance?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Rest Assured?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in embedded software development and testing for aerospace products?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Notice Period (In Days)": NOTICE_PERIOD_IN_DAYS,
    "What is your notice period? How soon can you take up this role ?": NOTICE_PERIOD_IN_DAYS,
    "How many years of experience do you have in Java Selenium?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in cypress?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have working in the aerospace domain?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have as a Software Tester?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Mainframes?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in Ui Automation?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in playwright?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Automation?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Selenium?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience you have in API?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Automation Test Framework?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience you have Postman?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience you have in Selenium?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Api Automation?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of exp in python coding": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Manual Testing?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Salesforce Testing?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in Selenium Automation?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of experience do you have in Javascript?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "What is your last working day?": NOTICE_PERIOD_IN_DAYS,
    "How many years of experience do you have in Python?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of Exp in Automation Python testing?": YEARS_OF_EXPERIENCE_IN_CORE,
    "How many years of total experience you have?": YEARS_OF_EXPERIENCE_IN_CORE,
    "What is your expected CTC in Lakhs per annum?": EXPECTED_CTC_NUMERIC,
    "Please confirm your availability for Virtual interview on 17th May 2025?": ANSWER_YES,
    "Current CTC": CURRENT_CTC_NUMERIC,
    "How many years of experience do you have in Application Engineering?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Are you open to work on contract?": ANSWER_YES,
    "Are you currently residing in Hyderabad, Telangana or willing to relocate to Hyderabad, Telangana?": ANSWER_YES,
    "Are you currently residing in Ahmedabad or willing to relocate to Ahmedabad?": ANSWER_YES,
    "do you have good experience in python?": ANSWER_YES,
    "Are you open to work in 10:00 AM To 07:00 PM for this job?": ANSWER_YES,
    "Are you willing to relocate to Pune to work in Hybrid mode on direct payroll with my client ?": ANSWER_YES,
    "Are you currently residing in Bengaluru or willing to relocate to Bengaluru?": ANSWER_YES,
    "This is a work from office opportunity. Are you willing to work full-time out of our office in Hebbal, Bangalore?": ANSWER_YES,
    "Do you have PF in your current company?": ANSWER_YES,
    "Are you currently residing in Hyderabad or willing to relocate to Hyderabad?": ANSWER_YES,
    "Are you currently residing in Gurugram, Haryana or willing to relocate to Gurugram, Haryana?": ANSWER_YES,
    "Are you willing to work 4 days a week from Office?": ANSWER_YES,
    "Are you ready to work on C2H Role?": ANSWER_YES,
    "Are you okay to relocate to bangalore": CURRENT_LOCATION_IS_BANGALORE,
    "How Many Years of exp you have in Data Engineering?": YEARS_OF_EXPERIENCE_IN_CORE,
    "Expected CTC (Numeric Input Only)": EXPECTED_CTC_FULL_NUMERIC,
    "Expected CTC (Numeric Inputs Only)": EXPECTED_CTC_FULL_NUMERIC,
    "What is your expected annual CTC in INR ?": EXPECTED_CTC_FULL_NUMERIC,
    "Current CTC (Numeric Input Only)": CURRENT_CTC_FULL_NUMERIC,
    "Current CTC (Numeric Inputs Only)": CURRENT_CTC_FULL_NUMERIC,
    "What is your expected CTC per annum in lakhs? (Mention Only Number) (For e.g. 10)": EXPECTED_CTC_NUMERIC,
    "What is your expected cost to company? (Please mention in LPA)": EXPECTED_CTC_NUMERIC,
    "What is your current CTC per annum in lakhs? (Mention Only Number) (For e.g. 10)": CURRENT_CTC_NUMERIC,
    "What is your current CTC in LPA?": CURRENT_CTC_NUMERIC,
    "What is your current cost to company? (Please mention in LPA)": CURRENT_CTC_NUMERIC,
    "What is your current CTC in Lakhs per annum?": CURRENT_CTC_NUMERIC,
    "What is your current annual CTC in INR ?": CURRENT_CTC_FULL_NUMERIC,
    "Notice Period": NOTICE_PERIOD_IN_DAYS,
    "What is your notice period?": NOTICE_PERIOD_IN_DAYS,
    "What is your current Notice Period?": NOTICE_PERIOD_IN_DAYS,
    "First Name": FIRST_NAME,
    "Date of Birth": DATE_OF_BIRTH,
    "Gender": GENDER,
    "Country Code": COUNTRY_CODE,
    "Last Name": LAST_NAME,
    "Current Location": CURRENT_LOCATION,
    "Preferred Location": CURRENT_LOCATION,
    "How many years of Experience do you have in ETL resting?": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many years of experience do you have in Mobile Testing?  ": YEARS_OF_EXPERIENCE_IN_NON_CORE,
    "How many relevant years of experience into Python development?": YEARS_OF_EXPERIENCE_IN_NON_CORE
}
