skip_titles = ["AppScan Product _Lead Performance Engineer _Remote Location",
                        "Remote Senior Software Engineer - 34123",
                        "#Jmeter #PerformanceTesting #BMCHelix #Product-Developer-III #5-6yrs",
                        "Technical Evaluator (Remote, Full-Time)",
                        "Senior Performance Engineer",
                        "Senior Site Reliability Engineer",
               "Site Reliability Engineer",
               "Senior Python Developer (genAI)",
               "Senior Data Warehouse Engineer",
                ".Net GenAI",
                "AIML Developer",
                "AIML Technical Lead | Noida | Hybrid Mode",
                "Analyst- Operations Performance & Analytics",
                "Architect - RPA",
                "Associate Lead Software Engineer",
                "Aws Devops Engineer",
                "AWS Pyspark DeveloperMachine Learning Engineer",
                "Azure Data Engineer",
                "Azure Data Engineer_Pune_Immediate",
                "Azure Developer_ P",
                "Azure Devops Developer",
                "Azure Devops Engineer",
                "Azure DevOps engineer with Data Engineering capabilities",
                "Azure Devops Professional",
                "C# React Full stack Developer",
                "CAD Developer",
                "Cloud Engineer",
                "Cloud Site Reliability Engineer",
                "Data Engineer",
                "Data Engineer - ETL/Python",
                "Data Engineer ( 4-5 years )",
                "Data Engineer ( 5-6 years )",
                "Data Engineer (AWS)",
                "Data scientist",
                "Deputy Manager",
                "Devops _2 To 5 years",
                "Dot Net Developer",
                "Dot Net Fullstack Developer",
                "Energy Expert",
                "Engineering Lead",
                "Engineering Lead - MERN & Python",
                "ETL Automation Testing",
                "Flutter .Net core full stack dev",
                "Full stack Developer (JavaScript + Python)",
                "Fullstack Developer",
                "GCP Data Engineer",
                "Gcp Engineer",
                "HCL is Hiring For Gen AI Developer",
                "Healthcare Research & Data Analyst",
                "Integration Consultant",
                "Java Backend Developer",
                "Java Developer with QA and Gen AI",
                "Lead Software Engineer (React)",
                "Looker Developer",
                "Maximo Consultant",
                "MERN & Cloud Lead Developer",
                "Microsoft fabric + Data bricks + Pyspark",
               "MIL/SIL Test Engineer",
                "NetSuite Application Developer",
                "Oracle EBS Technical Consultant",
                "Platform Engineer",
                "Python Developer",
                "Python Developer - Contract",
                "Python Developer (Face-To-Face Interview on 13th Sep) Chennai",
                "Python Developer Face To Face Interview on 6th Sep Sat in Bangalore",
                "Python Developer RAG AI",
                "Python GenAI Developer",
                "Quantitative Developer - C++/C#",
                "Security Ops Analyst",
                "Senior Data Engineer",
                "Senior Data Scientist (Artificial Intelligence Machine Learning)",
                "Senior Data Scientist, Actimize",
                        "Sr SAP Test Engineer",
                        "Sr. Performance Tester- Tietoevry Create ( m/f/d)",
               "Performance Tester",
                        "Java Test Automation",
                        "RPA Developer (Automation Anywhere A360)",
               "QE Automation (ETRM space ) || 4-10 YRS || Bangalore",
               "Quality Assurance Tester (KTA/Tungsten Experienced Only)",
                        "TDM Testing Engineer",
                        "SalesForce CPQ Automation",
               "Python pyspark Developer Infosys Pune/Bangalore",
               "Devops Automation Engineer",
               "Automation: RPA Developer",
               "Technical Lead - MERN / Python",
               "Sr. UX Designer",
               "Sr Full Stack Development with Generative AI || Immediate || Hybrid",
               "Snowflake Data Engineer",
               "Databricks Developer",
               "Agentic AI",
               "Artificial Intelligence Engineer",
               "Automation Tester-Katalon Studio",
               "Python Developer - Gen AI",
               "Senior Software Engineer - Java and AI at An E-commerce Unicorn",
               "Python Software Developer",
               "Healthcare Integration Engineer",
               "Quant Trader (AI/ML - Systematic Strategies)",
               "Aws Data Engineer",
               "RPA Developer - UiPath",
               "Network Python Automation Engineer",
               "Automation Tester (Tosca)",
               "Tosca Automation Tester",
               "Senior Java Software Engineer",
               "Ansible Automation",
                        "Senior Mobile testing Engineer (Appium )",
               "Java Software Engineer",
               "Senior Java Software Engineer",
               "Automation Engineer - Appium Expert",
               "NodeJS Developer (Immediate Joiner)",
               "Calypso Test Engineer",
               "NodeJS with Strapi CMS",
               "Tester - OBLM Data Validator – CPC Operations",
               "Lead Automation Engineer ( Trade Flow+ Investment Banking )",
               "Mulesoft Consultant",
               "Senior AI Developer -Intelligent Web Automation",
               "Senior Software Engineer (C / C++ with AWS)",
               "Tosca Automation Engineer",
               "QA Automation Engineer (Java + Kafka)-Remote/Contract",
               "Solutions Engineer, APAC",
               "1. ServiceNow – Now Assist Platform",
               "Entry Level Software Engineer",
               "Data Platform Engineer - Mumbai Hybrid (Contract) role",
               "C/C++ developer For New Zealand based Product comp in Pune Hybrid",
               "Virtualization & SIL Test Expert (4-8 Yrs)",
               "HIL Validation (4-8 Yrs)",
               "Sr. Test Automation Engineer with Java",
               "Senior QA Automation Engineer - Java Testing",
               "Junior QA Engineer (Full-time, 6-Month Contract)",
               "Data scientist / ML Engineer -- US Client (Analytics)",
               "SAS Risk modelling/Credit risk-- US MNC (analytics)",
               "Risk modelling/Credit risk-- US MNC (analytics)",
               "Data scientist Fraud modelling -- US Client (Analytics)",
               "data analyst / Data analytics - US MNC (Analytics)",
               "Retail analyst / Marketing analytics-- US MNC (Analytics)",
               "Machine Learning Engineer",
               "SRE Devops - Pan India",
               "Data Analyst",
               "C# Automation(Bangalore\Pune)",
               "Java Software Engineer",
               "Full-stack Developer",
               "Technical Lead",
               "SOAR / XSOAR Developer",
               "Software Performance Tools Developer",
               "Hiring Software Developers (Ahmedabad)",
               "AI Trainer",
               "Sql Consultant",
               "Sales Development Representative",
               "Senior Python Developer",
               "Synthetic Environment Developer(Modeling)",
               "Data Scientist",
               "Ai/ML Lead- Bangalore (Pan India Infosys)",
               "Sevilla Case: Engineer, AS",
               "SDET Engineer - Mobile",
               "Experienced Cybersecurity Engineer",
               "Lead MLOps Engineer",
               "AI Research Engineer",
               "Generative AI Engineer",
               "Devops Engineer",
               "Lead AI Engineer || Immediate Joiner || Hybrid || Bangalore",
               "Senior Devops Engineer",
               "Automation Engineer (n8n Expert)",
               "Assistant Manager - Data Science",
               "Ruby On Rails Developer",
               "Hiring For Generative AI- Developers",
               "Site Reliability Engineer-STG(P)",
               "Dot Net Full Stack Developer Azure & Gen AI",
               "Oracle Cloud ERP Security Consultant",
               "Python Developer / AI-ML Engineer | 2+ Years Exp | Bangalore | Aziro",
               "Fraud Strategy",
               "Power Platform Developer",
               "Python Developer@Infosys",
               "Firmware Testing Engineer",
               "Immediate Hiring | Power Platform Developer | PAN India",
               "RPA Developer",
               "Sql Developer",
               "QA Automation Engg - Desktop Mobile",
               "Hiring - Azure Data Factory Professional at Aspire ..!!",
               "Senior Azure Data Engineer",
               "QA Automation Engineer (Selenium + Java, ETL)",
               "Freelance QA Automation Engineer (Karate Framework – UI & API)",
               "n8n Specialist (Low/No Code)",
               "Azure Data Engineer- US MNC (analytics)",
                        "Senior Software Engineer",
               "Guidewire Tester",
               "Siebel Automation Tester",
               "Senior Quality Test Engineer (Copado Robotic Testing)",
               "Performance Test Engineer",
"ADAS Engineer",
"AI-ML Engineer",
"Compiler Engineer",
"Hiring For Automation Testing /SDET | HCLTech Nagpur",
"Multimedia Engineer",
"Oracle Retail ( MFCS) QA - Consultant / Senior Consultant",
"QA Mainframe Test Engg, AS",
"R&D Specialist",
"Salesforce Quality Analyst - Manual/Automation Testing",
"Senior AI/NLP Engineer",
"Software Developer",
"Software Engineer",
"SW Engineer",
               "ETL Developer",
                "AlgoNext Automation Developer, India",
                "Ekloud - Salesforce Quality Assurance Automation Engineer",
                "Test Engineer - Investment Data Platform",
                "Platform Automation Engineer",
                "Senior Platform Automation Engineer",
                      "System Development Engineer, Just Walk Out Tech",
                      'Senior Software Engineer Dev Perl REQ/0727',
                      "Senior AI Engineer",
               "Software Build/Install Engineer",
               "Technical Consultant",
                      "AI ENGINEERING SPECIALIST - AI ENGINEERING SPECIALIST",
                      "Optics Design & Test Engineer II",
                      "Member Of Technical Staff, DFM Firmware Engineer",
                      "Senior Engineer, ASIC Development Engineering",
                      "Associate Software Developer - C++ (Embedded)",
                      "Senior Software Development Engineer III - Distributed Systems",
                      "Senior Databricks Engineer",
                      "Senior Security Engineer",
                      "Databricks Developer - Python / SQL",
                      "Behavioural Scientist ( Part time)"]