skip_titles = ["AppScan Product _Lead Performance Engineer _Remote Location",
                        "Remote Senior Software Engineer - 34123",
                        "#Jmeter #PerformanceTesting #BMCHelix #Product-Developer-III #5-6yrs",
                        "Technical Evaluator (Remote, Full-Time)",
                        "Senior Performance Engineer",
                        "Senior Site Reliability Engineer",
                        "Sr SAP Test Engineer",
                        "Sr. Performance Tester- Tietoevry Create ( m/f/d)",
                        "Java Test Automation",
                        "RPA Developer (Automation Anywhere A360)",
               "QE Automation (ETRM space ) || 4-10 YRS || Bangalore",
               "Quality Assurance Tester (KTA/Tungsten Experienced Only)",
                        "TDM Testing Engineer",
                        "SalesForce CPQ Automation",
               "Python pyspark Developer Infosys Pune/Bangalore",
               "Devops Automation Engineer",
               "Databricks Developer",
               "Automation Tester-Katalon Studio",
               "Python Developer - Gen AI",
               "Senior Software Engineer - Java and AI at An E-commerce Unicorn",
               "Python Software Developer",
               "Healthcare Integration Engineer",
               "Quant Trader (AI/ML - Systematic Strategies)",
               "Aws Data Engineer",
               "RPA Developer - UiPath",
               "Network Python Automation Engineer",
               "Automation Tester (Tosca)",
               "Tosca Automation Tester",
               "Senior Java Software Engineer",
               "Ansible Automation",
                        "Senior Mobile testing Engineer (Appium )",
               "Java Software Engineer",
               "Senior Java Software Engineer",
               "Automation Engineer - Appium Expert",
               "NodeJS Developer (Immediate Joiner)",
               "Calypso Test Engineer",
               "NodeJS with Strapi CMS",
               "Tester - OBLM Data Validator – CPC Operations",
               "Lead Automation Engineer ( Trade Flow+ Investment Banking )",
               "Mulesoft Consultant",
               "Senior AI Developer -Intelligent Web Automation",
               "Senior Software Engineer (C / C++ with AWS)",
               "Tosca Automation Engineer",
               "QA Automation Engineer (Java + Kafka)-Remote/Contract",
               "Solutions Engineer, APAC",
               "1. ServiceNow – Now Assist Platform",
               "Entry Level Software Engineer",
               "Data Platform Engineer - Mumbai Hybrid (Contract) role",
               "C/C++ developer For New Zealand based Product comp in Pune Hybrid",
               "Virtualization & SIL Test Expert (4-8 Yrs)",
               "HIL Validation (4-8 Yrs)",
               "Sr. Test Automation Engineer with Java",
               "Senior QA Automation Engineer - Java Testing",
               "Junior QA Engineer (Full-time, 6-Month Contract)",
               "Data scientist / ML Engineer -- US Client (Analytics)",
               "SAS Risk modelling/Credit risk-- US MNC (analytics)",
               "Risk modelling/Credit risk-- US MNC (analytics)",
               "Data scientist Fraud modelling -- US Client (Analytics)",
               "data analyst / Data analytics - US MNC (Analytics)",
               "Retail analyst / Marketing analytics-- US MNC (Analytics)",
               "Machine Learning Engineer",
               "SRE Devops - Pan India",
               "Data Analyst",
               "C# Automation(Bangalore\Pune)",
               "Java Software Engineer",
               "Full-stack Developer",
               "Technical Lead",
               "SOAR / XSOAR Developer",
               "Software Performance Tools Developer",
               "Hiring Software Developers (Ahmedabad)",
               "AI Trainer",
               "Sql Consultant",
               "Sales Development Representative",
               "Senior Python Developer",
               "Synthetic Environment Developer(Modeling)",
               "Data Scientist",
               "Ai/ML Lead- Bangalore (Pan India Infosys)",
               "Sevilla Case: Engineer, AS",
               "SDET Engineer - Mobile",
               "Experienced Cybersecurity Engineer",
               "Lead MLOps Engineer",
               "AI Research Engineer",
               "Generative AI Engineer",
               "Devops Engineer",
               "Lead AI Engineer || Immediate Joiner || Hybrid || Bangalore",
               "Senior Devops Engineer",
               "Automation Engineer (n8n Expert)",
               "Assistant Manager - Data Science",
               "Ruby On Rails Developer",
               "Hiring For Generative AI- Developers",
               "Site Reliability Engineer-STG(P)",
               "Dot Net Full Stack Developer Azure & Gen AI",
               "Oracle Cloud ERP Security Consultant",
               "Python Developer / AI-ML Engineer | 2+ Years Exp | Bangalore | Aziro",
               "Fraud Strategy",
               "Power Platform Developer",
               "Python Developer@Infosys",
               "Firmware Testing Engineer",
               "Immediate Hiring | Power Platform Developer | PAN India",
               "RPA Developer",
               "Sql Developer",
               "QA Automation Engg - Desktop Mobile",
               "Hiring - Azure Data Factory Professional at Aspire ..!!",
               "Senior Azure Data Engineer",
               "Azure Data Engineer- US MNC (analytics)",
                        "Senior Software Engineer",
                      "System Development Engineer, Just Walk Out Tech",
                      'Senior Software Engineer Dev Perl REQ/0727',
                      "Senior AI Engineer",
                      "AI ENGINEERING SPECIALIST - AI ENGINEERING SPECIALIST",
                      "Optics Design & Test Engineer II",
                      "Member Of Technical Staff, DFM Firmware Engineer",
                      "Senior Engineer, ASIC Development Engineering",
                      "Associate Software Developer - C++ (Embedded)",
                      "Senior Software Development Engineer III - Distributed Systems",
                      "Senior Databricks Engineer",
                      "Senior Security Engineer",
                      "Databricks Developer - Python / SQL",
                      "Behavioural Scientist ( Part time)"]